# Generated by Django 3.2.3 on 2021-06-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskuser',
            name='ava',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
